all:
	@javac Arraynode.java
	@javac Arraylist.java
	@javac TrieNode.java
	@javac Trie.java
	@javac Node.java
	@javac MaxHeap.java
	@javac PointInterface.java
	@javac Point.java
	@javac EdgeInterface.java
	@javac Edge.java
	@javac TriangleInterface.java
	@javac Triangle.java
	@javac ShapeInterface.java
	@javac Shape.java
	@javac Driver.java
	@java Driver input.txt
	@rm *.class
